version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
      - login

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html

  login:
    build:
      context: ./login
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./login:/usr/share/nginx/html

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./worker/public:/usr/share/nginx/html

  db:
    image: mysql:8.0    # Specify the MySQL version
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password   # Replace with a secure password
      MYSQL_DATABASE: my_database          # Optional: Initial database to create
      MYSQL_USER: my_user                  # Optional: Non-root user
      MYSQL_PASSWORD: my_user_password     # Password for the non-root user
    ports:
      - "3306:3306"   # Map the container's MySQL port to the host
    volumes:
      - db_data:/var/lib/mysql   # Persist data on the host to retain data

volumes:
  db_data:      